name: facturacion_demo
description: "Demo de OptimizaciÃ³n de Pagos y Operaciones Financieras - CBLuna"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  
  # Navigation & routing
  go_router: ^14.6.2
  url_strategy: ^0.2.0
  url_launcher: ^6.2.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  pluto_grid: ^8.0.0
  syncfusion_flutter_charts: ^28.1.38
  google_fonts: ^6.2.1
  gap: ^3.0.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # File picker
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatares/
    - assets/images/isotipos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
